### ISSUE TITLE
Issue with IE10 due to setImmediate

### ISSUE THREAD

**Issue by sathishkumar-d** [CC-Archived/SWFService#2]
Hi,

First of all i would like to thank you for building this nice library. We are trying to make this work in IE10 and facing some issues. 

Mainly regards to the below line 
SWFService Line no 96

<pre><code>nextTick(function() {
            return schedule(pendingResolver);
          });
</code></pre>

the error in IE10 is 

> "TypeError: Function expected

Problem seems to be with setImmediate being set to a function in IE10 eventually nickTick being set to true instead of the function

<pre><code>
nextTick = (typeof process !== "undefined" && process !== null ? process.nextTick : void 0) || (typeof setImmediate !== "undefined" && setImmediate !== null) || function(task) {
    return setTimeout(task, 0);
  };
</code></pre>

What is impact of setImmediate check in the above condition?
Should the check be removed or specific condition needs to be added for IE before calling nickTick

Please let me know. 
Thanks in Advance

**Comment by johnyanarella** [comment]
The line you are referencing is from a prerelease build of SWFService 2.0 I had supplied earlier this year to a contractor at our mutual client.  There was a bug in that build where if `setImmediate` was detected, `nextTick` was set to `true` rather than to a reference to the `setImmediate` function itself.

If you look at the current code here on GitHub for the release version of 2.0, you'll see this CoffeeScript:

``` CoffeeScript
nextTick = if process?.nextTick? then process.nextTick else if setImmediate? then setImmediate else ( task ) -> setTimeout( task, 0 )
```

which compiles to this JavaScript:

``` JavaScript
nextTick = (typeof process !== "undefined" && process !== null ? process.nextTick : void 0) != null ? process.nextTick : typeof setImmediate !== "undefined" && setImmediate !== null ? setImmediate : function(task) {
    return setTimeout(task, 0);
  };
```

Could you grab the latest from Bower or here on GitHub and try again?

Please let me know if this problem persists with the release build.  Thanks!

**Comment by sathishkumar-d** [comment]
Sorry for the late reply yes it seems to be fixed based on the latest bower install. Thanks for your time.
